### ISSUE TITLE
Ships costs stub on wiki

### ISSUE THREAD

**Issue by janat08** [stjern90/hoi4_mod#4]
https://en.wikipedia.org/wiki/Costs_of_warships_1936-1945

It is empty right now, and I will not take fill data in, but I marked it as ww2 stub meaning its easy for historians to find. FYI USA inflation was up by 20%, and that may have occurred in other countries for purposes of balance of airpower that also would depend on scale of production which shipbuilding doesn't benefit so much from.

**Comment by janat08** [comment]
Alternatively ships can be priced by their displacement (weight) with various percentages of that across classifications accounting for armor. Additionaly as with airpower where you can mod airplanes by their configuration (high altitute heavy fighter or bomber escort). So increase range for speed, reduce cost for speed, although that wouldn't make much sense for if there's a custom naval tree which means that the ship types would ideally be already pre-configured historically towards strategic demands.

**Comment by Charles-Martel** [comment]
Did you make this wiki page? Holy cow lol nice job
Best way to price is probably by their tonnage, as you said, since ship costs are hard to convert into unified currency. I would recommend the tonnage while sent into battle (incl. ammo, personnel, etc.) rather than 'standard' weight

**Comment by janat08** [comment]
If you're looking ahead to doing this, you could use rough figure of 30% as accounting for armor (other than carriers perhaps) which is what I belief heavy cruisers will have. If you look at how much engines weigh than you can also get correlation between top speed and displacement. I'm against ammo and personnel figures since they're fairly variable with armament not infrequently changing on ships (where they could replace a turret with aa guns). The whole idea is to avoid having 30% inaccuracy by looking at prices of ships, where inflation can go up 20% in 2 years after war start.

I wouldn't mind scrapping the detailed navy tree altogether in favour of letting player decide what kind of ship he wants through modding the hull (with bonuses decided through displacement- armor + engines = armament).

**Comment by Charles-Martel** [comment]
I was probably not going to do this in the short-term, and probably not even in the long-term. Have other stuff that I want to do first which will take very long time (adding releasable nations, minor NF trees, major country localization / land unit balance)
